### ISSUE TITLE
Support off-cluster jaeger collector

### ISSUE THREAD

**Issue by krishofmans** [opentracing-contrib/nginx-opentracing#122]
Hello,

I was trying to enable opentracing/jaeger support for an nginx controller. 
The collector endpoint is not on the same cluster.

In the docs it just says a valid url, not necessarily a valid url on the cluster?
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#jaeger-collector-host

The url is https terminated and reachable from inside the pod.

But I just got
```
Error: exit status 1
2020/01/21 10:51:02 [error] 2228#2228: opentracing_propagate_context before tracer loaded
nginx: [error] opentracing_propagate_context before tracer loaded
nginx: configuration file /tmp/nginx-cfg185864836 test failed
```

Is this scenario supposed to be supported?
We have several spring boot applications that successfully use the collector endpoint.

Thanks,
Kind regards,
Kris

**Comment by BBQigniter** [comment]
We have the same error-message after trying to enable opentracing in combination with jaeger-agents

I used this manual: https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/opentracing/

So I created a daemonset for the jaeger-agent which looks like:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  namespace: apm
  labels:
    app: jaeger-agent
spec:
  selector:
    matchLabels:
      app: jaeger-agent
  template:
    metadata:
      labels:
        app: jaeger-agent
    spec:
      # added temporarily for testing purposes as it seems that the KEMP balancer with the current installed firmware-version doesn't support HTTP/2 well
      hostAliases:
      - ip: "10.12.100.11"
        hostnames:
        - "test-apm-server-grpc.somecorp.services"
      containers:
      - image: example-repo/jaegertracing/jaeger-agent:1.24
        name: jaeger-agent
        ports:
        # port names must not be longer than 15 chars
        #- name: jaeger-agent-thrift-compact-port
        - name: jatc-port
          containerPort: 6831
          protocol: UDP
        #- name: jaeger-agent-thrift-binary-port
        - name: jatb-port
          containerPort: 6832
          protocol: UDP
        #- name: jaeger-agent-serve-config-port
        - name: jasc-port
          containerPort: 5778
          protocol: TCP
        #- name: jaeger-agent-zipkin-thrift-compact-port
        - name: jaztc-port
          containerPort: 5775
          protocol: UDP
        #- name: jaeger-agent-admin-port
        - name: jaa-port
          containerPort: 14271
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 14271
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 14271
          initialDelaySeconds: 60
          periodSeconds: 5
        # as we use the "host.alias" workaround for the moment we need to skip cert-verification
        args: ["--reporter.grpc.host-port=test-apm-server-grpc.somecorp.services:30443", "--reporter.grpc.tls.enabled=true", "--agent.tags='elastic-apm-auth=Bearer supersecurekey'", "--reporter.grpc.tls.skip-host-verify=true"]
        resources:
          requests:
            memory: 1Gi
            cpu: 0.1
          limits:
            memory: 1Gi
            # so it cannot take all CPUs if something is wrong
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: apm
  labels:
    app: jaeger-agent
spec:
  selector:
    app: jaeger-agent
  ports:
  - name: jatc-port
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: jatb-port
    port: 6832
    targetPort: 6832
    protocol: UDP
  - name: jasc-port
    port: 5778
    targetPort: 5778
    protocol: TCP
  - name: jaztc-port
    port: 5775
    targetPort: 5775
    protocol: UDP
  - name: jaa-port
    port: 14271
    targetPort: 14271
    protocol: TCP
```

the agent seems to be running fine in it's own namespace, logs looking ok

then we have a small test image which should create some traces - the yaml is:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jurisdictions
  name: jurisdictions
  namespace: dev-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jurisdictions
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jurisdictions
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        image: example.repo/bold/test/jurisdiction:testapm
        imagePullPolicy: Always
        name: jurisdictions
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
      imagePullSecrets:
      - name: example
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 256
          name: global.logging
          optional: false
        name: logging
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jurisdictions
  name: jurisdictions
  namespace: dev-team
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jurisdictions
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    jaeger-collector-host: "jaeger-agent.apm.svc.cluster.local"
    jaeger-collector-port: "6831"
    # also tried with this - nope
    #jaeger-sampler-host: "http://jaeger-agent.apm.svc.cluster.local"
    #jaeger-sampler-port: "5778"
    jaeger-service-name: "jurisdictions-nginx"
  labels:
    app: jurisdictions
  name: jurisdictions
  namespace: dev-team
spec:
  ingressClassName: "int-ingress-nginx"
  rules:
  - host: jurisdictions-testapm.lab
    http:
      paths:
      - backend:
          serviceName: jurisdictions
          servicePort: 80
        path: /
```


I tried this on 2 different kubernetes-clusters, one with nginx-ingress 0.35 and another one with 0.41 - both end up with the error-message

```
nginx: [error] opentracing_propagate_context before tracer loaded
```

from inside the nginx-ingress containers the "jaeger-agent.apm.svc.cluster.local" ports are reachable as far as I have seen.
