### ISSUE TITLE
Bypass Jaeger agent for Jaeger collector does not work

### ISSUE THREAD

**Issue by ghost** [opentracing-contrib/nginx-opentracing#129]
I am trying to setup nginx so that the spans are directly sent to the Jaeger Collector on port 14268. Currently, I have no issues sending my spans to an agent and then relayed to the collector via port 14250 but when I change my `jaeger-config.yaml` to use `endpoint` instead of `localAgentHostPort` I can no longer find my traces in the panel. I have also run `tcpdump` in my container and get no traffic on port `14268`, but get periodic traffic on port `6831` when it is enabled. Is the endpoints feature in the jaeger cpp module also supported in nginx-opentracing?

The configuration I am referencing is this one: https://github.com/jaegertracing/jaeger-client-cpp#connecting-directly-to-the-collector

Jaeger-config.yaml
```yaml
service_name: nginx
disabled: false
sampler:
  type: const
  param: 1
reporter:
  logSpans: true
  localAgentHostPort: "jaeger-agent:6831" # This will work
  # endpoint: "jaeger-collector:14268/api/traces" # This won't work
```

Nginx.conf
```
load_module modules/ngx_http_opentracing_module.so;

events {}

http {
  opentracing_load_tracer /usr/local/lib/libjaegertracing_plugin.so /etc/jaeger-config.yaml;
  opentracing on;

  upstream ping {
    server ping-service:8000;
  }

  server {
    error_log /var/log/nginx/debug.log debug;
    listen 8080;
    server_name localhost;

    location = / {
      opentracing_trace_locations off;
      proxy_pass http://ping;
      opentracing_propagate_context;
    }
  }
}
```

Docker Compose
```yaml
version: '3.3'
services:

  ping-service:
    build:
      context: ../ping-service
      dockerfile: ./Dockerfile
    restart: on-failure
    # expose:
    #   - "8000"
    # ports:
    #   - "8000:8000"

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
    ports:
      - "14269"
      - "14268:14268"
      - "14250"
      - "9411:9411"
    restart: on-failure
    depends_on:
      - cassandra-schema

  nginx:
    image: opentracing/nginx-opentracing
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./jaeger-config.yaml:/etc/jaeger-config.yaml
    restart: on-failure
    expose:
      - "8080"
    ports:
      - "8080:8080"

  jaeger-query:
    image: jaegertracing/jaeger-query
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    depends_on:
      - cassandra-schema

  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    depends_on:
      - jaeger-collector

  cassandra:
    image: cassandra:3.9

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema
    depends_on:
      - cassandra
```
