### ISSUE TITLE
localAgentHostPort from env variable

### ISSUE THREAD

**Issue by rredkovich** [opentracing-contrib/nginx-opentracing#68]
Cannot find any examples nor issues with this question, could an environment variable be used to set agent host?

Context: a jaeger agent is placed on every node in kubernetes deployment and to eliminate extra time consumption packets should be send straight to node IP. Node IP could be set dynamically into env var:
```yaml
        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```
